// Generated by CoffeeScript 1.7.1
(function() {
  var assert, kwfn;

  assert = require("assert");

  kwfn = require('./index');

  describe('', function() {
    return describe('#keywordFunction()', function() {
      var fn;
      fn = kwfn(function(foo, bar) {
        return foo + bar;
      });
      it('should pass', function() {
        assert.equal('foobar', fn({
          foo: 'foo',
          bar: 'bar'
        }));
        return assert.equal(3, fn({
          foo: 1,
          bar: 2
        }));
      });
      it('should complain when extra argument passed', function() {
        var error;
        try {
          return fn({
            foo: 1,
            baz: 2
          });
        } catch (_error) {
          error = _error;
          return assert.equal(error.message, "Unexpected param 'baz'");
        }
      });
      it('should pass when no arguemt passed', function() {
        return fn();
      });
      return it('should complain when wrong argument passed', function() {
        var error;
        try {
          return fn('foo');
        } catch (_error) {
          error = _error;
          return assert.equal(error.message, "Unexpected param 'foo'");
        }
      });
    });
  });

}).call(this);
